### ISSUE TITLE
Use handlebars/runtime

### ISSUE THREAD

**Issue by JSteunou** [emaphp/handlebars-template-loader#1]
First, thanks for this loader, so other one make me crazy.

Second, do you think it will be possible to export content with handlebars/runtime instead of handlebars so final build got lighter?

**Comment by emaphp** [comment]
Actually I tried in the past to achieve that but i couldn't get it to work. Glad you found this package useful. Both PRs #2 and #3 are now merged into master. Changes are now available in v0.5.2. Thanks @JSteunou !

**Comment by JSteunou** [comment]
Nice, quick release, thank you!
