### ISSUE TITLE
Forward query param to Hbs compile options

### ISSUE THREAD

**Issue by JSteunou** [emaphp/handlebars-template-loader#14]
Hi there, long time ;)

it could be nice to forward options from query params to `precompile` call. I need some of [those options](http://handlebarsjs.com/reference.html) but cannot use it.

I could make a PR, should not be hard to do, I'm just a bit confused between `query` & `this.options` from inside the loader.

**Comment by emaphp** [comment]
ok, this could be nice. I was in the middle of refactoring all tests so it might take me a while to finally merge your PR. will do.

**Comment by JSteunou** [comment]
:/ I should have make this PR earlier, I could use it, like, tomorrow :D

**Comment by emaphp** [comment]
I didn't expect to add any new feature to this release but this seems nice. You'll find these changes on `0.7.0`, which was just published. Thx again @JSteunou.

**Comment by JSteunou** [comment]
Awesome ! Thank you very much !
