### ISSUE TITLE
Weird README

### ISSUE THREAD

**Issue by milewski** [emaphp/handlebars-template-loader#22]
Weirdness everywhere... is this loader dead? why readme is all messed up?

**Comment by milewski** [comment]
<img width="1128" alt="screen shot 2017-06-03 at 10 13 15 pm" src="https://cloud.githubusercontent.com/assets/2874967/26754269/e9ba2a10-48a9-11e7-90f7-7a2d94214e82.png">

**Comment by emaphp** [comment]
There, it's fixed now. I had to install grip to actually understand how github renders these files. I was (and still am) very busy at work so I couldn't give any time to any of my projects. To be honest, I'm not using this project for quite a while now...
