### ISSUE TITLE
question about installation

### ISSUE THREAD

**Issue by ckot** [emaphp/handlebars-template-loader#25]
forgive me if this is a stupid question (I'm a server-side person trying to throw together a front-end app), but should this be installed with either --save or --save-dev so that it's permanently in the package.json?  The fact that you need to import 'handlebars-template-loader/runtime' makes me think it should be --save

**Comment by emaphp** [comment]
hi, this is a development package so it should be installed using --save-dev. sorry for the late answer.

**Comment by ckot** [comment]
gotcha. that makes sense.
