### ISSUE TITLE
Webpack 4 Support

### ISSUE THREAD

**Issue by philostler** [emaphp/handlebars-template-loader#26]
This loader doesn't work with the latest version of Webpack (4).

```sh
Module build failed: TypeError: Cannot read property 'macros' of undefined
    at Object.module.exports (/node_modules/handlebars-template-loader/index.js:64:22)
```
Is due to this code...
```js
if (this.options.macros instanceof Object ) {
    _extend(macros, this.options.macros);
}
```
In the [Webpack v4 loader migration guide](https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202), `this.options` has been removed.

> Guideline: Loaders should receive all options via this.query.

**Comment by emaphp** [comment]
Hi, I just published an updated version. Couldn't make it in time to update all tests but, if the migration guide is correct, you shouldn't have any problems.

**Comment by philostler** [comment]
Works great @emaphp! Thanks for an extremely rapid turn around!
