### ISSUE TITLE
NPM 3 PeerDependencies Issue

### ISSUE THREAD

**Issue by bassettsj** [emaphp/handlebars-template-loader#4]
> "We will also be changing the behavior of peerDependencies in npm@3. We won’t be automatically downloading the peer dependency anymore. Instead, we’ll warn you if the peer dependency isn’t already installed. This requires you to resolve peerDependency conflicts yourself, manually, but in the long run this should make it less likely that you’ll end up in a tricky spot with your packages’ dependencies."

Should probably move handlebar as a dependency to help resolve these issue.

**Comment by emaphp** [comment]
hello @bassettsj, I appreciate your collaboration. I've followed a lot of discussion regarding this subject (specially here: https://github.com/npm/npm/issues/6565). As far as I understand, we developers shouldn't worry about modifying peerDependencies. As one of the users points out:

> Peerdependency now means - "I want this package, but I won't install it myself - I will re-use the one used by the app I'm being used in, and I'll warn if it isn't present".

I'm pretty sure that this approach will please the vast majority of the users using this package. Giving the developer this responsability would improve compatibility with older projects using handlebars (as a matter of fact, this loader works with versions 2 and above). Adding handlebars as a dependency will only silence the warning messages, which will be removed once npm 3 is released.

I'm pretty sure other users might have an opinion regarding this topic so I'll leave this issue open so we can discuss further which actions to take. It might be better just to remove handlebars from any of the dependencies and add a warning message in the docs like we did with underscore-template-loader.

**Comment by bassettsj** [comment]
@emaphp Thanks for your great reply.

> "It might be better just to remove handlebars from any of the dependencies and add a warning message in the docs like we did with underscore-template-loader."

I think that could be a good solution. We are running a really old version of handlebars in our app and kept getting SMV conflicts from it. Thought maybe moving it to the dependencies might help, but I think you're right that might not be a great approach. Let me close the PR.

**Comment by emaphp** [comment]
I've just published a new release through npm. You'll find these changes in v0.5.4. Thanks again for your collaboration,

**Comment by bassettsj** [comment]
Thanks!
