### ISSUE TITLE
handlebars gets bundled

### ISSUE THREAD

**Issue by ptbrowne** [emaphp/handlebars-template-loader#7]
Hi,

Thanks for your loader, it works very well.

The only problem is that in the README, it is written that for helpers I should use `require('handlebars-template-loader').Handlebars`.

My problem is that when I do that, webpack complains (and the whole Handlebars gets bundled):

```
WARNING in /Users/pbrowne/code/hupp/app/~/handlebars/lib/index.js
require.extensions is not supported by webpack. Use a loader instead.

WARNING in /Users/pbrowne/code/hupp/app/~/handlebars/lib/index.js
require.extensions is not supported by webpack. Use a loader instead.

WARNING in /Users/pbrowne/code/hupp/app/~/handlebars/lib/index.js
require.extensions is not supported by webpack. Use a loader instead.
```

What I did was to use directly `require('handlebars/runtime')` to register my partials and helpers.

**Comment by ptbrowne** [comment]
I opened https://github.com/emaphp/handlebars-template-loader/pull/8

This way, you require only the handlebars runtime, through `handlebars-template-loader` though.

``` js
// partials.js

var Handlebars = require('handlebars-template-loader/runtime');

Handlebars.registerHelper('toto', function () {
   ....
});
```

**Comment by emaphp** [comment]
Already merged, closing (thx again).
