### ISSUE TITLE
@require macro not passing context

### ISSUE THREAD

**Issue by andreyd-mindojo** [emaphp/handlebars-template-loader#9]
I'm trying to do simple thing with following code:
`parent.hbs`

```
<div class="parent">
  {{cntxt.value}}
  @require('child.hbs')
</div>
```

`child.hbs`

```
<div class="child">{{cntxt.value}}</div>
```

then process it with

```
parentTemplate = require 'path/to/parent.hbs'
parentTemplate({cntxt: {value: 'VALUE'}})
```

the result is following:

```
<div class="parent">
  VALUE
  <div class="child"></div>
</div>
```

So i cannot access `cntxt` in child component. 
What am i doing wrong?

**Comment by emaphp** [comment]
Hi @andrey-dresvyannikov, coul you try with a previous version of the package? Try using 0.5.3 and check if the problem persists.

**Comment by emaphp** [comment]
I did my own test and turns out that using handlebars >= 4.0.0 might trigger this error. Is that your case?

**Comment by andreyd-mindojo** [comment]
@emaphp yep, i'm using handlebars 4.0.5
will try with that version a bit later

**Comment by emaphp** [comment]
Could you try installing handlebars 3 instead?

``` bash
sudo npm install handlebars@3.0.0 --save
```

Let me know if that works for you.

**Comment by andreyd-mindojo** [comment]
@emaphp yep, it works ok with handlebars 3.0.0
do you know what's need to be done to make it compatible with handlebars >= 4.0.0?

**Comment by emaphp** [comment]
I'll do my research comparing the output of both versions. I'll update this issue accordingly. Thanks for making me notice.

**Comment by emaphp** [comment]
I found the issue. Turns out that since v4.0, Handlebars invokes helpers using an additional argument called "container". For some reason, this breaks the way how context is passed from parent templates. I'll push a new version after I come with a solution working in both versions.

**Comment by emaphp** [comment]
I've managed to find a solution by checking the number of arguments passed to the helper wrapper. I've tested with a sample project and it looks like it's working. Both v3 and v4 of Handlebars should be working now. Update your packages to v0.5.7 and let me know if this works for you.

**Comment by andreyd-mindojo** [comment]
@emaphp great! Will try it today and update thread.

**Comment by andreyd-mindojo** [comment]
@emaphp works with `handlebars-template-loader 0.5.7` and `handlebars 4.0.5`! Thank you!
